### ISSUE TITLE
[ Feature Request ] - Healthcare company strict search

### ISSUE THREAD

**Issue by xNS5** [fastenhealth/fasten-onprem#355] opened 2023-12-10 22:46 UTC
Presently when searching for a healthcare company, fasten (I believe) performs a loose search on provider names. When I search for my specific provider's name, it returns 4,091 results which is pretty daunting to search through. As it turns out, my specific provider isn't included in the list despite getting over 4,000 hits.

I'd like to propose that by default, the provider search be more of a strict search. If the provider isn't included, fasten should let the user know that. For users that need more of a loose search, perhaps a simple checkbox could be made available to allow a loose search. Alternatively, a more advanced search interface with different search parameters be available such as by geographic location, connection interface, provider specialty, etc.

**Comment by AnalogJ** [comment] 2024-12-25 21:10
Great idea, working on functionality like this right now! 

closing as a dupe of https://github.com/fastenhealth/fasten-onprem/issues/507

**Closed by AnalogJ** 2024-12-25 21:10 UTC
