### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by aarons3225** [fastenhealth/fasten-onprem#407] opened 2024-02-05 03:33 UTC
### Contact Details

aaron.sabol@outlook.com

### What happened?

when trying to connect, I get this error. I am a member of United Healthcare, and I go to their site, I am able to login. However, it won't connect.

### Flavor

Docker

### Version

main

### Relevant log output

```shell
{
  "source_id": "00000000-0000-0000-0000-000000000000",
  "brand_id": "5863477c-a178-41fc-b9f4-c881f9e8dbca",
  "checkpoint_data": {
    "brand_id": "5863477c-a178-41fc-b9f4-c881f9e8dbca",
    "code_challenge_method": "S256",
    "endpoint_id": "577a6af3-9fb6-43e2-8bdf-920cf435fe3b",
    "portal_id": "3f7e0791-7bab-46cb-be35-c9729c653eb0",
    "state": "b5b65b68-9adf-411a-922c-5dae7b4ce1c0"
  },
  "error_data": {
    "error": "{\"message\":\"callback error: access_denied, description: Member eligibility failed - no eligible membership found.\",\"line\":1,\"column\":2689421,\"sourceURL\":\"http://192.168.0.11:9090/web/main.97a6711b9e540231.js\",\"stack\":\"@http://192.168.0.11:9090/web/main.97a6711b9e540231.js:1:2689421\\nDe@http://192.168.0.11:9090/web/polyfills.5ca82281f9682ff9.js:1:215358\\nkt@http://192.168.0.11:9090/web/polyfills.5ca82281f9682ff9.js:1:215586\\n@http://192.168.0.11:9090/web/polyfills.5ca82281f9682ff9.js:1:215661\\ne@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:3050\\n@http://192.168.0.11:9090/web/polyfills.5ca82281f9682ff9.js:1:215528\\nonInvoke@http://192.168.0.11:9090/web/main.97a6711b9e540231.js:1:114502\\n@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:2295\\n@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:2801\\nonInvokeTask@http://192.168.0.11:9090/web/main.97a6711b9e540231.js:1:114322\\n@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:2962\\nm@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:10278\\n@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:9051\\ny@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:45:709\\n_@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:45:1069\"}",
    "stack": "@http://192.168.0.11:9090/web/main.97a6711b9e540231.js:1:2689421\nDe@http://192.168.0.11:9090/web/polyfills.5ca82281f9682ff9.js:1:215358\nkt@http://192.168.0.11:9090/web/polyfills.5ca82281f9682ff9.js:1:215586\n@http://192.168.0.11:9090/web/polyfills.5ca82281f9682ff9.js:1:215661\ne@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:3050\n@http://192.168.0.11:9090/web/polyfills.5ca82281f9682ff9.js:1:215528\nonInvoke@http://192.168.0.11:9090/web/main.97a6711b9e540231.js:1:114502\n@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:2295\n@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:2801\nonInvokeTask@http://192.168.0.11:9090/web/main.97a6711b9e540231.js:1:114322\n@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:2962\nm@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:10278\n@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:9051\ny@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:45:709\n_@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:45:1069",
    "summary": "An error occurred while initializing external data source connection: '{\"message\":\"callback error: access_denied, description: Member eligibility failed - no eligible membership found.\",\"line\":1,\"column\":2689421,\"sourceURL\":\"http://192.168.0.11:9090/web/main.97a6711b9e540231.js\",\"stack\":\"@http://192.168.0.11:9090/web/main.97a6711b9e540231.js:1:2689421\\nDe@http://192.168.0.11:9090/web/polyfills.5ca82281f9682ff9.js:1:215358\\nkt@http://192.168.0.11:9090/web/polyfills.5ca82281f9682ff9.js:1:215586\\n@http://192.168.0.11:9090/web/polyfills.5ca82281f9682ff9.js:1:215661\\ne@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:3050\\n@http://192.168.0.11:9090/web/polyfills.5ca82281f9682ff9.js:1:215528\\nonInvoke@http://192.168.0.11:9090/web/main.97a6711b9e540231.js:1:114502\\n@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:2295\\n@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:2801\\nonInvokeTask@http://192.168.0.11:9090/web/main.97a6711b9e540231.js:1:114322\\n@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:2962\\nm@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:10278\\n@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:9051\\ny@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:45:709\\n_@http://192.168.0.11:9090/web/assets/js/lforms/assets/lib/zone.min.js:45:1069\"}'"
  }
}
```

**Comment by AnalogJ** [comment] 2024-02-05 04:23
Hey @aarons3225 
Unfortunately this isn't a bug -- see #318 

---


After contacting UHC vendor support, they responded with the following message (emphasis mine):

> FLEX was designed to be in compliance with the[ CMS Final rule](https://www.federalregister.gov/documents/2020/05/01/2020-05050/medicare-and-medicaid-programs-patient-protection-and-affordable-care-act-interoperability-and). Eligibility errors generally occurs when the member has a UHC plan but not one that falls under the umbrella of that rule so they are not currently eligible for FLEX. If a member sees an eligibility error please confirm **they have a plan that falls into one of the categories listed there and not a commercial plan.**

This is similar to the error that Aetna users encounter - #33 

> This functionality is currently only available to members of health plans under certain government programs, like Medicare, Medicaid, and Qualified Health Plans on the Federally Facilitated Exchanges. Aetna’s commercial health plans are not supported. You may use this platform to share data with third-party apps if you are a member of any of the following plans:
>
> source: [aetnabetterhealth.com/share-health-data-guide.html](https://www.aetnabetterhealth.com/share-health-data-guide.html)


I'm going to close this issue as a dupe of #318, but it is something that we need to provide a better/clearer error message for.

**Closed by AnalogJ** 2024-02-05 04:23 UTC
Labels: bug
