### ISSUE TITLE
[Bug]: Blue Cross Blue Shield of Alabama not working

### ISSUE THREAD

**Issue by Alf626** [fastenhealth/fasten-onprem#438] opened 2024-03-02 00:15 UTC
### What happened?

Can't connect to Blue Cross Blue Shield of Alabama.  Just spins when trying to connect. 

Patient Portal address appears to be missing: https://www.bcbsal.org/mybluecross

### Flavor

Docker

### Version

 main#05a6840

**Comment by AnalogJ** [comment] 2024-12-25 20:59
Anthem/Blue Cross is known to be broken right now, but we should have a fix shortly. 

Closing this as a dupe of #470

**Closed by AnalogJ** 2024-12-25 20:59 UTC
Labels: bug
