### ISSUE TITLE
[Suggestion]: Allow me to search by URL in connections

### ISSUE THREAD

**Issue by havedill** [fastenhealth/fasten-onprem#497] opened 2024-08-09 14:11 UTC
### What happened?

I was trying to search for 

"Chicago Health Medical Group" 

and got lots of unrelated results. However if I could have searched by the **portal url** i would have easily found it nested inside of this group, under a different name

![image](https://github.com/user-attachments/assets/cc0514d4-cda6-455e-98b0-a52483cfc217)

![image](https://github.com/user-attachments/assets/3a943ccc-0d07-4f7b-a2d4-34c0e8f7575a)

My portal URL is https://18552-1.portal.athenahealth.com/, which actually translates to "LAKEFRONT MEDICAL ASSOCIATES"

Had i simply been able to search for that it would make finding my providers easier

### Flavor

Docker

### Version

latest

**Comment by AnalogJ** [comment] 2024-12-25 20:22
Agreed, we're working on this right now. 

Closing this as a dupe of #507

**Closed by AnalogJ** 2024-12-25 20:22 UTC
Labels: bug
