### ISSUE TITLE
[Provider Request]: Virginia Mason Franciscan Health - Virginia Mason Medical Center

### ISSUE THREAD

**Issue by bear454** [fastenhealth/fasten-onprem#477] opened 2024-06-05 19:06 UTC
### Contact Details

james@bear454.com

### Provider/Institution Name

Virginia Mason Medical Center

### Provider/Institution Website

https://www.vmfh.org/our-hospitals/virginia-mason-medical-center

### Patient Portal Login Website

https://cernerhealth.com/oauth/authenticate?redirect_uri=https%3A%2F%2Fcernerhealth.com%2Fsaml%2Fsso%2Fresponse%3Fmessage_id%3D_e248c1ce-9795-4ac6-93cc-9c2d88ad7ce6%26issuer%3Dhttps%253A%252F%252Fvirginiamason.patientportal.us-1.healtheintent.com%252Fsession-api%252Fprotocol%252Fsaml2%252Fmetadata&sign_in_only=on&client_id=f7d237cd49f44e93a0f46f1112cb11d2

### Provider EHR Platform

Cerner

### Anything else we should know?

Other VMFH sites use Epic MyChart, but VMMC Seattle uses Cerner.

**Comment by AnalogJ** [comment] 2024-06-05 19:16
Hey @bear454 I already see `Virginia Mason Medical Center` supported in the app. Are you having issues pulling your records from the institution?

**Comment by bear454** [comment] 2024-06-08 02:15
:facepalm:  I saw the Virginia Mason Franciscan Health entry (why is Epic), didn't recognize there was already a separate entry, sorry.

The logo is wrong for VMMC, though, but that's a minor nitpick.

**Comment by AnalogJ** [comment] 2024-06-12 05:19
agreed, the logo needs to be fixed. let me reopen this issue.

**Comment by AnalogJ** [comment] 2024-12-25 20:38
closing this as a dupe of #531

**Closed by AnalogJ** 2024-12-25 20:38 UTC
Labels: enhancement, provider
