### ISSUE TITLE
[Bug]: Anthem and Anthem Blue Cross reporting "The client application is not known or is not authorized."

### ISSUE THREAD

**Issue by parknicker** [fastenhealth/fasten-onprem#519] opened 2024-09-12 00:11 UTC
### What happened?

I receive the following error on the Anthem side when trying to sync with either Anthem or Anthem Blue Cross:

The client application is not known or is not authorized.

<img width="731" alt="Screenshot 2024-09-11 at 5 10 15 PM" src="https://github.com/user-attachments/assets/c55eebcc-c385-4c91-b7b5-7dcfd0dd4261">

### Flavor

Docker

### Version

main#93bc252

**Comment by srwareham** [comment] 2024-10-12 08:12
This can probably be consolidated under https://github.com/fastenhealth/fasten-onprem/issues/470. Same problem but you can find the context there

**Comment by AnalogJ** [comment] 2024-12-25 20:04
Closing this as a dupe of #470 

@parknicker sorry about this. It's a known issue (Anthem migrated to a new API provider) but we should have this fixed soon.

**Closed by AnalogJ** 2024-12-25 20:04 UTC
Labels: bug
