### ISSUE TITLE
non-USA healthcare providers? 

### ISSUE THREAD

**Issue by nikolaydubina** [fastenhealth/fasten-onprem#466] opened 2024-04-28 06:46 UTC
is there support/plan for Hong Kong, Korea, UK, Japan ?

**Comment by AnalogJ** [comment] 2024-04-28 14:01
Hey @nikolaydubina yes, we do plan to support international healthcare institutions. However this support usually depends on Patient Access rights & legislation within these countries (patient accessible FHIR endpoints are not usually enabled by default). 

Closing this issue as a dupe of #42 - If you've done any research regarding HK, Korea, Japan's patient access API's, please add it to that issue.

**Closed by AnalogJ** 2024-04-28 14:01 UTC
